// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Swift_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean Touchpress;
        
        public Valve.VR.SteamVR_Action_Vector2 TouchPos;
        
        public Valve.VR.SteamVR_Action_Boolean Menu;
        
        public Valve.VR.SteamVR_Action_Boolean Grip;
        
        public Valve.VR.SteamVR_Action_Boolean Interact;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonRightHand;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonLeftHand;
        
        public Valve.VR.SteamVR_Action_Pose Pose;
        
        public Valve.VR.SteamVR_Action_Boolean Touchpad;
    }
}
